import time

from selenium import webdriver
from selenium.webdriver.common.keys import Keys
import time
driver = webdriver.Chrome()

driver.get('https://www.saucedemo.com/')
time.sleep(2)
user_name = driver.find_element('xpath', '//*[@id="user-name"]')
user_name.send_keys('standard_user')
password = driver.find_element('xpath', '//*[@id="password"]')
password.send_keys('secret_sauce')
login = driver.find_element('xpath', '//*[@id="login-button"]')
login.click()
time.sleep(2)
add_to_cart = driver.find_element('xpath', '//*[@id="add-to-cart-sauce-labs-backpack"]')
add_to_cart.click()
time.sleep(2)
cart = driver.find_element('xpath', '//*[@id="shopping_cart_container"]/a')
cart.click()
time.sleep(2)
checkout = driver.find_element('xpath', '//*[@id="checkout"]')
checkout.click()
time.sleep(2)
first_name = driver.find_element('xpath', '//*[@id="first-name"]')
first_name.send_keys('julia')
last_name = driver.find_element('xpath', '//*[@id="last-name"]')
last_name.send_keys('aleksandrova')
postal_code = driver.find_element('xpath', '//*[@id="postal-code"]')
postal_code.send_keys('12915')
time.sleep(2)
cont = driver.find_element('xpath', '//*[@id="continue"]')
cont.click()
time.sleep(2)
end = driver.find_element('xpath', '//*[@id="finish"]')
end.click()
time.sleep(2)
back = driver.find_element('xpath', '//*[@id="back-to-products"]')
back.click()
time.sleep(2)
search = driver.find_element('xpath', '//*[@id="menu_button_container"]/div/div[1]/div')
search.click()
time.sleep(2)
logout = driver.find_element('xpath', '//*[@id="logout_sidebar_link"]')
logout.click()
time.sleep(2)


